# Generated by Django 5.2.8 on 2025-12-29 01:10

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_number", models.CharField(max_length=10, verbose_name="房号")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "4.楼房房号",
                "verbose_name_plural": "4.楼房房号列表",
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="社区名称")),
                (
                    "office_address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="办公地址"
                    ),
                ),
                (
                    "office_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="办公电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "1.社区",
                "verbose_name_plural": "1.社区列表",
            },
        ),
        migrations.CreateModel(
            name="HousingEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="小区名称")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="小区地址"
                    ),
                ),
                (
                    "property_company",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="物业公司"
                    ),
                ),
                (
                    "property_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="物业电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.community",
                        verbose_name="所属社区",
                    ),
                ),
            ],
            options={
                "verbose_name": "1.小区",
                "verbose_name_plural": "1.小区列表",
                "unique_together": {("name", "community")},
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="楼栋名称/编号")),
                (
                    "building_type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "多层"), (2, "高层")],
                        null=True,
                        verbose_name="建筑类型",
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(blank=True, null=True, verbose_name="总层数"),
                ),
                (
                    "units_per_floor",
                    models.IntegerField(blank=True, null=True, verbose_name="一层几户"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.housingestate",
                        verbose_name="所属小区",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.楼栋",
                "verbose_name_plural": "2.楼栋列表",
            },
        ),
        migrations.CreateModel(
            name="Hutong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="胡同名称/编号")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.community",
                        verbose_name="所属社区",
                    ),
                ),
            ],
            options={
                "verbose_name": "5.胡同",
                "verbose_name_plural": "5.胡同列表",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "notification_type",
                    models.SmallIntegerField(
                        choices=[(1, "紧急"), (2, "普通"), (3, "活动")],
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "notification_time_type",
                    models.SmallIntegerField(
                        choices=[(1, "长期"), (2, "定期")],
                        default=1,
                        verbose_name="通知时间类型",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="有效期至"
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="阅读次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. 通知",
                "verbose_name_plural": "2. 通知列表",
                "ordering": ["-publish_time"],
            },
        ),
        migrations.CreateModel(
            name="NotificationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=api.models.upload_to_notification_attachments,
                        verbose_name="附件文件",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="附件描述"
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.notification",
                        verbose_name="关联通知",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 通知附件",
                "verbose_name_plural": "3. 通知附件列表",
            },
        ),
        migrations.CreateModel(
            name="ResidentialAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.SmallIntegerField(
                        choices=[(1, "楼房"), (2, "平房")], verbose_name="地址类型"
                    ),
                ),
                (
                    "is_resident",
                    models.SmallIntegerField(
                        choices=[(1, "自住"), (2, "租住"), (3, "空房")],
                        default=3,
                        verbose_name="居住状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.apartment",
                        verbose_name="楼房房号",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.building",
                        verbose_name="所属楼栋",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.housingestate",
                        verbose_name="所属小区",
                    ),
                ),
                (
                    "hutong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.hutong",
                        verbose_name="所属胡同",
                    ),
                ),
            ],
            options={
                "verbose_name": "7.居住地址",
                "verbose_name_plural": "7.居住地址列表",
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "household_number",
                    models.CharField(max_length=15, unique=True, verbose_name="户号"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=20, verbose_name="房主姓名"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "residential_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.residentialaddress",
                        verbose_name="居住地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.家庭",
                "verbose_name_plural": "2.家庭列表",
            },
        ),
        migrations.CreateModel(
            name="SingleHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_number", models.CharField(max_length=10, verbose_name="房号")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "hutong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.hutong",
                        verbose_name="所属胡同",
                    ),
                ),
            ],
            options={
                "verbose_name": "6.平房房号",
                "verbose_name_plural": "6.平房房号列表",
            },
        ),
        migrations.AddField(
            model_name="residentialaddress",
            name="single_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.singlehouse",
                verbose_name="平房房号",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="单元名称/编号")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.building",
                        verbose_name="所属楼栋",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.单元",
                "verbose_name_plural": "3.单元列表",
            },
        ),
        migrations.AddField(
            model_name="residentialaddress",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.unit",
                verbose_name="所属单元",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unit",
                verbose_name="所属单元",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[
                            (1, "超级管理员"),
                            (2, "管理员"),
                            (3, "书记"),
                            (4, "社工"),
                        ],
                        default=2,
                        verbose_name="角色",
                    ),
                ),
                (
                    "department",
                    models.SmallIntegerField(
                        choices=[(1, "社区办"), (2, "社区"), (3, "其他")],
                        default=3,
                        verbose_name="部门",
                    ),
                ),
                (
                    "is_baned",
                    models.BooleanField(
                        default=True, verbose_name="账户状态（True:正常, False:禁用）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. 用户扩展信息",
                "verbose_name_plural": "1. 用户扩展信息列表",
            },
        ),
        migrations.CreateModel(
            name="SocialWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生年月"),
                ),
                (
                    "is_secretary",
                    models.BooleanField(default=False, verbose_name="是否为书记"),
                ),
                (
                    "is_baned",
                    models.BooleanField(
                        default=True, verbose_name="是否在职（True:在职, False:离职）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.community",
                        verbose_name="所属社区",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.userprofile",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.社区工作者",
                "verbose_name_plural": "2.社区工作者列表",
            },
        ),
        migrations.CreateModel(
            name="Cadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生年月"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="职务"
                    ),
                ),
                (
                    "is_baned",
                    models.BooleanField(
                        default=True, verbose_name="是否在职（True:在职, False:离职）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.userprofile",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 干部",
                "verbose_name_plural": "3. 干部列表",
            },
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notification",
                        verbose_name="通知",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "4. 通知阅读状态",
                "verbose_name_plural": "4. 通知阅读状态列表",
                "unique_together": {("notification", "user")},
            },
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "gender",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "男"), (2, "女")],
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "nationality",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "汉族"),
                            (2, "蒙古族"),
                            (3, "回族"),
                            (4, "藏族"),
                            (5, "维吾尔族"),
                            (6, "苗族"),
                            (7, "彝族"),
                            (8, "壮族"),
                            (9, "布依族"),
                            (10, "朝鲜族"),
                            (11, "满族"),
                            (12, "侗族"),
                            (13, "瑶族"),
                            (14, "白族"),
                            (15, "土家族"),
                            (16, "哈尼族"),
                            (17, "哈萨克族"),
                            (18, "傣族"),
                            (19, "黎族"),
                            (20, "傈僳族"),
                            (21, "佤族"),
                            (22, "畲族"),
                            (23, "高山族"),
                            (24, "拉祜族"),
                            (25, "水族"),
                            (26, "东乡族"),
                            (27, "纳西族"),
                            (28, "景颇族"),
                            (29, "柯尔克孜族"),
                            (30, "土族"),
                            (31, "达斡尔族"),
                            (32, "仫佬族"),
                            (33, "羌族"),
                            (34, "布朗族"),
                            (35, "撒拉族"),
                            (36, "毛难族"),
                            (37, "仡佬族"),
                            (38, "锡伯族"),
                            (39, "阿昌族"),
                            (40, "普米族"),
                            (41, "塔吉克族"),
                            (42, "怒族"),
                            (43, "乌孜别克族"),
                            (44, "俄罗斯族"),
                            (45, "鄂温克族"),
                            (46, "崩龙族"),
                            (47, "保安族"),
                            (48, "裕固族"),
                            (49, "京族"),
                            (50, "塔塔尔族"),
                            (51, "独龙族"),
                            (52, "鄂伦春族"),
                            (53, "赫哲族"),
                            (54, "门巴族"),
                            (55, "珞巴族"),
                            (56, "基诺族"),
                            (57, "其他"),
                        ],
                        null=True,
                        verbose_name="民族",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_id_card",
                                message="身份证号格式不正确",
                                regex="^\\d{17}[\\dXx]$",
                            )
                        ],
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "political_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "中国共产党党员"),
                            (2, "中国共产党预备党员"),
                            (3, "中国共产主义青年团团员"),
                            (4, "中国国民党革命委员会党员"),
                            (5, "中国民主同盟盟员"),
                            (6, "中国民主建国会会员"),
                            (7, "中国民主促进会会员"),
                            (8, "中国农工民主党党员"),
                            (9, "中国致公党党员"),
                            (10, "九三学社社员"),
                            (11, "台湾民主自治同盟盟员"),
                            (12, "无党派民主人士"),
                            (13, "群众"),
                        ],
                        null=True,
                        verbose_name="政治面貌",
                    ),
                ),
                (
                    "marital_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "未婚"), (2, "已婚"), (3, "离异"), (4, "丧偶")],
                        null=True,
                        verbose_name="婚姻状态",
                    ),
                ),
                (
                    "education",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "文盲"),
                            (2, "小学"),
                            (3, "初中"),
                            (4, "高中"),
                            (5, "大专"),
                            (6, "本科"),
                            (7, "硕士"),
                            (8, "博士"),
                            (9, "其他"),
                        ],
                        null=True,
                        verbose_name="学历",
                    ),
                ),
                ("job", models.BooleanField(default=False, verbose_name="是否有工作")),
                (
                    "is_dead",
                    models.BooleanField(default=False, verbose_name="是否死亡"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.family",
                        verbose_name="所属家庭",
                    ),
                ),
            ],
            options={
                "verbose_name": "1.居民",
                "verbose_name_plural": "1.居民列表",
                "indexes": [
                    models.Index(fields=["id_card"], name="idx_resident_id_card")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="family",
            index=models.Index(
                fields=["household_number"], name="idx_family_household_number"
            ),
        ),
    ]
