# Generated by Django 5.2.8 on 2025-12-19 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationread",
            options={
                "verbose_name": "4. 通知阅读状态",
                "verbose_name_plural": "4. 通知阅读状态列表",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_time_type",
            field=models.SmallIntegerField(
                choices=[(1, "长期"), (2, "定期")],
                default=1,
                verbose_name="通知时间类型",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="有效期至"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.SmallIntegerField(
                choices=[(1, "超级管理员"), (2, "管理员"), (3, "书记"), (4, "社工")],
                default=2,
                verbose_name="角色",
            ),
        ),
        migrations.CreateModel(
            name="NotificationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="notification_attachments/", verbose_name="附件文件"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="附件描述"
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.notification",
                        verbose_name="关联通知",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 通知附件",
                "verbose_name_plural": "3. 通知附件列表",
            },
        ),
    ]
