# Generated by Django 5.2.8 on 2025-12-22 01:43

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_notificationread_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
        migrations.AddField(
            model_name="socialworker",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.userprofile",
                verbose_name="关联用户",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_baned",
            field=models.BooleanField(
                default=True, verbose_name="是否在职（True:在职, False:离职）"
            ),
        ),
        migrations.AlterField(
            model_name="notificationattachment",
            name="file",
            field=models.FileField(
                upload_to=api.models.upload_to_notification_attachments,
                verbose_name="附件文件",
            ),
        ),
        migrations.CreateModel(
            name="Cadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生年月"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="职务"
                    ),
                ),
                (
                    "is_baned",
                    models.BooleanField(
                        default=True, verbose_name="是否在职（True:在职, False:离职）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.userprofile",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 干部",
                "verbose_name_plural": "3. 干部列表",
            },
        ),
    ]
