# Generated by Django 5.2.8 on 2025-12-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_userprofile_name_remove_userprofile_phone_and_more"),
    ]

    operations = []
